- name: conditions
  hosts: local
  connection: local
  vars:
    numbers: 5
  tasks:
  - name: check number is less than 10 or not
    ansible.builtin.degug:
      msg: "Given number {{ number }} is less than 10"
    when: number < 10